// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhMcB6Ytc6X4JrC5pnTJxJEkWRwJENJHE',
    appId: '1:819772531199:web:1a452af14b4aff983847ca',
    messagingSenderId: '819772531199',
    projectId: 'mu-ict',
    authDomain: 'mu-ict.firebaseapp.com',
    databaseURL: 'https://mu-ict-default-rtdb.firebaseio.com',
    storageBucket: 'mu-ict.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvTIdyQCWhtXtht3-txvrtZJ7ErES_SyA',
    appId: '1:819772531199:android:158c06af5df2ca143847ca',
    messagingSenderId: '819772531199',
    projectId: 'mu-ict',
    databaseURL: 'https://mu-ict-default-rtdb.firebaseio.com',
    storageBucket: 'mu-ict.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCelZTuIixDQ64W1mRaEWdQKkN4hDtuK8Y',
    appId: '1:819772531199:ios:db12e6c5bdc6f3823847ca',
    messagingSenderId: '819772531199',
    projectId: 'mu-ict',
    databaseURL: 'https://mu-ict-default-rtdb.firebaseio.com',
    storageBucket: 'mu-ict.appspot.com',
    iosBundleId: 'com.ictmarwadi.ict',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCelZTuIixDQ64W1mRaEWdQKkN4hDtuK8Y',
    appId: '1:819772531199:ios:0f7b7c322a7b808e3847ca',
    messagingSenderId: '819772531199',
    projectId: 'mu-ict',
    databaseURL: 'https://mu-ict-default-rtdb.firebaseio.com',
    storageBucket: 'mu-ict.appspot.com',
    iosBundleId: 'com.ictmarwadi.ict.RunnerTests',
  );
}
